import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import Provider from "./provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className="bg-black text-white flex flex-col min-h-screen">
        <header className="bg-gray-900 text-white py-4 fixed top-0 w-full z-10 border-b border-gray-700">
          <nav className="container mx-auto flex justify-around">
            <Link href="/">HOME</Link>
            <Link href="/champions">Champion List</Link>
            <Link href="/items">Item List</Link>
            <Link href="/rotation">Champion Rotation</Link>
          </nav>
          <Provider>{children}</Provider>
        </header>

        <main className="flex-1 pt-[70px] pb-[50px]">{children}</main>
        <footer className="bg-gray-900 p-4 w-full mt-auto">
          <div className="container mx-auto text-center text-gray-400 text-sm">
            [Your Product Name] is not endorsed by Riot Games and does not
            reflect the views or opinions of Riot Games or anyone officially
            involved in producing or managing Riot Games properties. Riot Games
            and all associated properties are trademarks or registered
            trademarks of Riot Games, Inc.
          </div>
        </footer>
      </body>
    </html>
  );
}
